const route = (
    method,
    path,
    featureCode,
    featureLabel,
    actionCode,
    actionLabel,
    targetType,
    targetParam,
) => ({
    method,
    path,
    featureCode,
    featureLabel,
    actionCode,
    actionLabel,
    targetType,
    targetParam,
});

const USER_ACTIVITY_ROUTES = [
    // Tài khoản và hồ sơ
    route(
        "POST",
        "/api/users/create",
        "account",
        "Tài khoản",
        "CREATE",
        "Tạo tài khoản",
        "user",
    ),
    route(
        "POST",
        "/api/users/create/batch",
        "account",
        "Tài khoản",
        "CREATE",
        "Tạo nhiều tài khoản",
        "user",
    ),
    route(
        "POST",
        "/api/users/import-accounts",
        "account",
        "Tài khoản",
        "IMPORT",
        "Nhập tài khoản từ Excel",
        "user",
    ),
    route(
        "DELETE",
        "/api/users/bulk",
        "account",
        "Tài khoản",
        "DELETE",
        "Xóa nhiều tài khoản",
        "user",
    ),
    route(
        "PUT",
        "/api/users/update-profile-required",
        "account",
        "Tài khoản",
        "UPDATE",
        "Hoàn tất cập nhật hồ sơ",
        "user",
    ),
    route(
        "PATCH",
        "/api/users/batch-status",
        "account",
        "Tài khoản",
        "UPDATE",
        "Cập nhật trạng thái nhiều tài khoản",
        "user",
    ),
    route(
        "PUT",
        "/api/users/:userId",
        "account",
        "Tài khoản",
        "UPDATE",
        "Cập nhật tài khoản",
        "user",
        "userId",
    ),
    route(
        "DELETE",
        "/api/users/:userId",
        "account",
        "Tài khoản",
        "DELETE",
        "Xóa tài khoản",
        "user",
        "userId",
    ),
    route(
        "PATCH",
        "/api/users/:userId/status",
        "account",
        "Tài khoản",
        "UPDATE",
        "Cập nhật trạng thái tài khoản",
        "user",
        "userId",
    ),
    route(
        "POST",
        "/api/students/import-update",
        "account",
        "Tài khoản",
        "IMPORT",
        "Nhập cập nhật sinh viên",
        "student",
    ),
    route(
        "POST",
        "/api/students/import-eligibility",
        "account",
        "Tài khoản",
        "IMPORT",
        "Nhập điều kiện đăng ký sinh viên",
        "student",
    ),
    route(
        "PUT",
        "/api/students/project-eligibility",
        "account",
        "Tài khoản",
        "UPDATE",
        "Cập nhật điều kiện đăng ký đồ án",
        "student",
    ),
    route(
        "PUT",
        "/api/students/intern-eligibility",
        "account",
        "Tài khoản",
        "UPDATE",
        "Cập nhật điều kiện đăng ký thực tập",
        "student",
    ),
    route(
        "PUT",
        "/api/students/specialization-eligibility",
        "account",
        "Tài khoản",
        "UPDATE",
        "Cập nhật điều kiện đăng ký chuyên ngành",
        "student",
    ),
    route(
        "PUT",
        "/api/lecturers/update-role/:lecturerId",
        "account",
        "Tài khoản",
        "UPDATE",
        "Cập nhật vai trò giảng viên",
        "lecturer",
        "lecturerId",
    ),
    route(
        "PUT",
        "/api/lecturers/update-limit/:lecturerId",
        "account",
        "Tài khoản",
        "UPDATE",
        "Cập nhật giới hạn hướng dẫn",
        "lecturer",
        "lecturerId",
    ),
    route(
        "PUT",
        "/api/roles/assign-role",
        "account",
        "Tài khoản",
        "UPDATE",
        "Gán vai trò",
        "role",
    ),
    route(
        "PUT",
        "/api/roles/remove-role",
        "account",
        "Tài khoản",
        "DELETE",
        "Gỡ vai trò",
        "role",
    ),
    route(
        "PUT",
        "/api/roles/assign-all-role",
        "account",
        "Tài khoản",
        "UPDATE",
        "Gán vai trò hàng loạt",
        "role",
    ),
    route(
        "PUT",
        "/api/roles/remove-all-role",
        "account",
        "Tài khoản",
        "DELETE",
        "Gỡ vai trò hàng loạt",
        "role",
    ),
    route(
        "PUT",
        "/api/info/update",
        "account",
        "Tài khoản",
        "UPDATE",
        "Cập nhật thông tin cá nhân",
        "user",
    ),
    route(
        "POST",
        "/api/info/upload-avatar",
        "account",
        "Tài khoản",
        "UPLOAD",
        "Tải ảnh đại diện lên",
        "user",
    ),
    route(
        "PUT",
        "/api/password/change",
        "account",
        "Tài khoản",
        "UPDATE",
        "Đổi mật khẩu",
        "user",
    ),

    // Năm học, nội dung, cấu hình
    route(
        "POST",
        "/api/academic-years",
        "academic-year",
        "Năm học",
        "CREATE",
        "Tạo năm học",
        "academic-year",
    ),
    route(
        "PUT",
        "/api/academic-years/:academicYearId",
        "academic-year",
        "Năm học",
        "UPDATE",
        "Cập nhật năm học",
        "academic-year",
        "academicYearId",
    ),
    route(
        "DELETE",
        "/api/academic-years/:academicYearId",
        "academic-year",
        "Năm học",
        "DELETE",
        "Xóa năm học",
        "academic-year",
        "academicYearId",
    ),
    route(
        "POST",
        "/api/news",
        "news",
        "Tin tức",
        "CREATE",
        "Tạo tin tức",
        "news",
    ),
    route(
        "PUT",
        "/api/news/:id",
        "news",
        "Tin tức",
        "UPDATE",
        "Cập nhật tin tức",
        "news",
        "id",
    ),
    route(
        "DELETE",
        "/api/news/:id",
        "news",
        "Tin tức",
        "DELETE",
        "Xóa tin tức",
        "news",
        "id",
    ),
    route(
        "POST",
        "/api/homepages/news",
        "homepage",
        "Trang chủ",
        "CREATE",
        "Tạo tin trang chủ",
        "homepage-news",
    ),
    route(
        "PUT",
        "/api/homepages/news/:id",
        "homepage",
        "Trang chủ",
        "UPDATE",
        "Cập nhật tin trang chủ",
        "homepage-news",
        "id",
    ),
    route(
        "DELETE",
        "/api/homepages/news/:id",
        "homepage",
        "Trang chủ",
        "DELETE",
        "Xóa tin trang chủ",
        "homepage-news",
        "id",
    ),
    route(
        "PUT",
        "/api/homepages/layout",
        "homepage",
        "Trang chủ",
        "UPDATE",
        "Cập nhật bố cục trang chủ",
        "homepage-layout",
    ),
    route(
        "POST",
        "/api/notifications",
        "notification",
        "Thông báo",
        "CREATE",
        "Gửi thông báo",
        "notification",
    ),
    route(
        "PUT",
        "/api/notifications/:notificationId",
        "notification",
        "Thông báo",
        "UPDATE",
        "Cập nhật thông báo",
        "notification",
        "notificationId",
    ),
    route(
        "DELETE",
        "/api/notifications/:id",
        "notification",
        "Thông báo",
        "DELETE",
        "Xóa thông báo",
        "notification",
        "id",
    ),
    route(
        "POST",
        "/api/notifications/intern-group",
        "notification",
        "Thông báo",
        "CREATE",
        "Gửi thông báo nhóm thực tập",
        "notification",
    ),
    route(
        "PUT",
        "/api/committees/config/:type",
        "committee-config",
        "Cấu hình hội đồng",
        "UPDATE",
        "Cập nhật cấu hình hội đồng",
        "committee-config",
        "type",
    ),
    route(
        "PUT",
        "/api/committees/time-location/:type/:committeeId",
        "committee-config",
        "Cấu hình hội đồng",
        "UPDATE",
        "Cập nhật thời gian và địa điểm hội đồng",
        "committee",
        "committeeId",
    ),
    route(
        "POST",
        "/api/evaluations/clos/pi",
        "evaluation",
        "Chấm điểm",
        "CREATE",
        "Tạo chỉ số PI",
        "pi",
    ),
    route(
        "PUT",
        "/api/evaluations/clos/pi/:piId",
        "evaluation",
        "Chấm điểm",
        "UPDATE",
        "Cập nhật chỉ số PI",
        "pi",
        "piId",
    ),
    route(
        "DELETE",
        "/api/evaluations/clos/pi/:piId",
        "evaluation",
        "Chấm điểm",
        "DELETE",
        "Xóa chỉ số PI",
        "pi",
        "piId",
    ),
    route(
        "POST",
        "/api/evaluations/clos",
        "evaluation",
        "Chấm điểm",
        "CREATE",
        "Tạo chuẩn đầu ra CLO",
        "clo",
    ),
    route(
        "PUT",
        "/api/evaluations/clos/:cloId",
        "evaluation",
        "Chấm điểm",
        "UPDATE",
        "Cập nhật chuẩn đầu ra CLO",
        "clo",
        "cloId",
    ),
    route(
        "DELETE",
        "/api/evaluations/clos/:cloId",
        "evaluation",
        "Chấm điểm",
        "DELETE",
        "Xóa chuẩn đầu ra CLO",
        "clo",
        "cloId",
    ),
    route(
        "POST",
        "/api/evaluations/clos/copy",
        "evaluation",
        "Chấm điểm",
        "CREATE",
        "Sao chép chuẩn đầu ra CLO",
        "clo",
    ),
    route(
        "POST",
        "/api/evaluations/forms",
        "evaluation",
        "Chấm điểm",
        "CREATE",
        "Tạo biểu mẫu đánh giá",
        "evaluation-form",
    ),
    route(
        "PUT",
        "/api/evaluations/forms/:evaluationId",
        "evaluation",
        "Chấm điểm",
        "UPDATE",
        "Cập nhật biểu mẫu đánh giá",
        "evaluation-form",
        "evaluationId",
    ),
    route(
        "DELETE",
        "/api/evaluations/forms/:evaluationId",
        "evaluation",
        "Chấm điểm",
        "DELETE",
        "Xóa biểu mẫu đánh giá",
        "evaluation-form",
        "evaluationId",
    ),
    route(
        "POST",
        "/api/evaluations/forms/copy",
        "evaluation",
        "Chấm điểm",
        "CREATE",
        "Sao chép biểu mẫu đánh giá",
        "evaluation-form",
    ),
    route(
        "PUT",
        "/api/evaluations/forms/indicators/:evaluationId",
        "evaluation",
        "Chấm điểm",
        "UPDATE",
        "Cập nhật tiêu chí đánh giá",
        "evaluation-form",
        "evaluationId",
    ),
    route(
        "POST",
        "/api/maintenance/enable",
        "maintenance",
        "Bảo trì",
        "UPDATE",
        "Bật chế độ bảo trì",
        "maintenance",
    ),
    route(
        "POST",
        "/api/maintenance/disable",
        "maintenance",
        "Bảo trì",
        "UPDATE",
        "Tắt chế độ bảo trì",
        "maintenance",
    ),

    // Doanh nghiệp và chuyên ngành
    route(
        "POST",
        "/api/companies/delete",
        "company",
        "Doanh nghiệp",
        "DELETE",
        "Xóa doanh nghiệp",
        "company",
    ),
    route(
        "POST",
        "/api/companies/import-excel",
        "company",
        "Doanh nghiệp",
        "IMPORT",
        "Nhập doanh nghiệp từ Excel",
        "company",
    ),
    route(
        "POST",
        "/api/companies/create/:companyId",
        "company",
        "Doanh nghiệp",
        "CREATE",
        "Tạo doanh nghiệp",
        "company",
        "companyId",
    ),
    route(
        "PUT",
        "/api/companies/update/:companyId",
        "company",
        "Doanh nghiệp",
        "UPDATE",
        "Cập nhật doanh nghiệp",
        "company",
        "companyId",
    ),
    route(
        "POST",
        "/api/specializations/registrations",
        "specialization",
        "Chuyên ngành",
        "CREATE",
        "Đăng ký chuyên ngành",
        "specialization-registration",
    ),
    route(
        "PUT",
        "/api/specializations/registrations",
        "specialization",
        "Chuyên ngành",
        "UPDATE",
        "Cập nhật đăng ký chuyên ngành",
        "specialization-registration",
    ),
    route(
        "POST",
        "/api/specializations/registrations/delete",
        "specialization",
        "Chuyên ngành",
        "DELETE",
        "Xóa đăng ký chuyên ngành",
        "specialization-registration",
    ),
    route(
        "GET",
        "/api/specializations/registrations/:studentId/cv/download",
        "specialization",
        "Chuyên ngành",
        "DOWNLOAD",
        "Tải CV đăng ký chuyên ngành",
        "student",
        "studentId",
    ),
    route(
        "GET",
        "/api/specializations/registrations/export/excel",
        "specialization",
        "Chuyên ngành",
        "EXPORT",
        "Xuất danh sách đăng ký chuyên ngành",
        "specialization-registration",
    ),
    route(
        "POST",
        "/api/specializations/timelines",
        "specialization",
        "Chuyên ngành",
        "CREATE",
        "Tạo mốc thời gian chuyên ngành",
        "specialization-timeline",
    ),
    route(
        "PUT",
        "/api/specializations/timelines/:key",
        "specialization",
        "Chuyên ngành",
        "UPDATE",
        "Cập nhật mốc thời gian chuyên ngành",
        "specialization-timeline",
        "key",
    ),
    route(
        "DELETE",
        "/api/specializations/timelines/:key",
        "specialization",
        "Chuyên ngành",
        "DELETE",
        "Xóa mốc thời gian chuyên ngành",
        "specialization-timeline",
        "key",
    ),
    route(
        "POST",
        "/api/specializations",
        "specialization",
        "Chuyên ngành",
        "CREATE",
        "Tạo chuyên ngành",
        "specialization",
    ),
    route(
        "PUT",
        "/api/specializations/:id",
        "specialization",
        "Chuyên ngành",
        "UPDATE",
        "Cập nhật chuyên ngành",
        "specialization",
        "id",
    ),
    route(
        "DELETE",
        "/api/specializations/:id",
        "specialization",
        "Chuyên ngành",
        "DELETE",
        "Xóa chuyên ngành",
        "specialization",
        "id",
    ),

    // Thực tập
    route(
        "POST",
        "/api/interns/registrations",
        "internship",
        "Thực tập tốt nghiệp",
        "CREATE",
        "Đăng ký thực tập",
        "intern-registration",
    ),
    route(
        "PUT",
        "/api/interns/registrations",
        "internship",
        "Thực tập tốt nghiệp",
        "UPDATE",
        "Cập nhật đăng ký thực tập",
        "intern-registration",
    ),
    route(
        "PUT",
        "/api/interns/registrations/status-intern/:id",
        "internship",
        "Thực tập tốt nghiệp",
        "UPDATE",
        "Cập nhật trạng thái đăng ký thực tập",
        "intern-registration",
        "id",
    ),
    route(
        "PUT",
        "/api/interns/registrations/company/assign-students",
        "internship",
        "Thực tập tốt nghiệp",
        "UPDATE",
        "Phân sinh viên vào doanh nghiệp",
        "intern-registration",
    ),
    route(
        "POST",
        "/api/interns/registrations/delete",
        "internship",
        "Thực tập tốt nghiệp",
        "DELETE",
        "Xóa đăng ký thực tập",
        "intern-registration",
    ),
    route(
        "POST",
        "/api/interns/registrations/cv",
        "internship",
        "Thực tập tốt nghiệp",
        "UPLOAD",
        "Tải CV thực tập lên",
        "intern-registration",
    ),
    route(
        "POST",
        "/api/interns/registrations/accepted-company-proof/evidence",
        "internship",
        "Thực tập tốt nghiệp",
        "UPLOAD",
        "Tải minh chứng doanh nghiệp tiếp nhận lên",
        "intern-registration",
    ),
    route(
        "GET",
        "/api/interns/registrations/:studentId/cv/download",
        "internship",
        "Thực tập tốt nghiệp",
        "DOWNLOAD",
        "Tải CV thực tập",
        "student",
        "studentId",
    ),
    route(
        "GET",
        "/api/interns/registrations/cv/export",
        "internship",
        "Thực tập tốt nghiệp",
        "EXPORT",
        "Xuất kho CV thực tập",
        "intern-registration",
    ),
    route(
        "GET",
        "/api/interns/registrations/evidence/export",
        "internship",
        "Thực tập tốt nghiệp",
        "EXPORT",
        "Xuất minh chứng thực tập",
        "intern-registration",
    ),
    route(
        "GET",
        "/api/interns/registrations/assigned-company/export",
        "internship",
        "Thực tập tốt nghiệp",
        "EXPORT",
        "Xuất danh sách phân doanh nghiệp",
        "intern-registration",
    ),
    route(
        "GET",
        "/api/interns/registrations/students/unregistered/export",
        "internship",
        "Thực tập tốt nghiệp",
        "EXPORT",
        "Xuất sinh viên chưa đăng ký thực tập",
        "intern-registration",
    ),
    route(
        "GET",
        "/api/interns/registrations/self-contact/export",
        "internship",
        "Thực tập tốt nghiệp",
        "EXPORT",
        "Xuất sinh viên tự liên hệ doanh nghiệp",
        "intern-registration",
    ),
    route(
        "GET",
        "/api/interns/registrations/register-wish/export",
        "internship",
        "Thực tập tốt nghiệp",
        "EXPORT",
        "Xuất nguyện vọng thực tập",
        "intern-registration",
    ),
    route(
        "POST",
        "/api/interns/temporary-results/register-wish/allocate",
        "internship",
        "Thực tập tốt nghiệp",
        "UPDATE",
        "Phân bổ nguyện vọng thực tập",
        "intern-result",
    ),
    route(
        "GET",
        "/api/interns/temporary-results/export",
        "internship",
        "Thực tập tốt nghiệp",
        "EXPORT",
        "Xuất kết quả thực tập tạm thời",
        "intern-result",
    ),
    route(
        "GET",
        "/api/interns/final-results/export",
        "internship",
        "Thực tập tốt nghiệp",
        "EXPORT",
        "Xuất kết quả thực tập",
        "intern-result",
    ),
    route(
        "GET",
        "/api/interns/final-results/classes/export",
        "internship",
        "Thực tập tốt nghiệp",
        "EXPORT",
        "Xuất danh sách lớp thực tập",
        "intern-result",
    ),
    route(
        "POST",
        "/api/interns/final-results/import",
        "internship",
        "Thực tập tốt nghiệp",
        "IMPORT",
        "Nhập kết quả thực tập",
        "intern-result",
    ),
    route(
        "POST",
        "/api/interns/final-results/import/undo",
        "internship",
        "Thực tập tốt nghiệp",
        "DELETE",
        "Hoàn tác nhập kết quả thực tập",
        "intern-result",
    ),
    route(
        "POST",
        "/api/interns/report-files/upload",
        "internship",
        "Thực tập tốt nghiệp",
        "UPLOAD",
        "Tải báo cáo thực tập lên",
        "intern-report",
    ),
    route(
        "GET",
        "/api/interns/report-files/download",
        "internship",
        "Thực tập tốt nghiệp",
        "DOWNLOAD",
        "Tải báo cáo thực tập",
        "intern-report",
    ),
    route(
        "POST",
        "/api/interns/groups/assign-students",
        "internship",
        "Thực tập tốt nghiệp",
        "UPDATE",
        "Phân nhóm thực tập",
        "intern-group",
    ),
    route(
        "POST",
        "/api/interns/timelines",
        "internship",
        "Thực tập tốt nghiệp",
        "CREATE",
        "Tạo mốc thời gian thực tập",
        "internship-timeline",
    ),
    route(
        "PUT",
        "/api/interns/timelines/:key",
        "internship",
        "Thực tập tốt nghiệp",
        "UPDATE",
        "Cập nhật mốc thời gian thực tập",
        "internship-timeline",
        "key",
    ),
    route(
        "DELETE",
        "/api/interns/timelines/:key",
        "internship",
        "Thực tập tốt nghiệp",
        "DELETE",
        "Xóa mốc thời gian thực tập",
        "internship-timeline",
        "key",
    ),

    // Đồ án tốt nghiệp
    route(
        "POST",
        "/api/projects",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "CREATE",
        "Đăng ký đồ án",
        "project",
    ),
    route(
        "POST",
        "/api/projects/admin-register",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "CREATE",
        "Đăng ký đồ án cho sinh viên",
        "project",
    ),
    route(
        "PUT",
        "/api/projects/admin-update/:projectId",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPDATE",
        "Cập nhật đồ án cho sinh viên",
        "project",
        "projectId",
    ),
    route(
        "POST",
        "/api/projects/import-excel",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "IMPORT",
        "Nhập đăng ký đồ án",
        "project",
    ),
    route(
        "DELETE",
        "/api/projects",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "DELETE",
        "Xóa đồ án",
        "project",
    ),
    route(
        "PUT",
        "/api/projects",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPDATE",
        "Cập nhật đồ án",
        "project",
    ),
    route(
        "PUT",
        "/api/projects/status-project/:projectId",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPDATE",
        "Cập nhật trạng thái đồ án",
        "project",
        "projectId",
    ),
    route(
        "PUT",
        "/api/projects/all-status-project",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPDATE",
        "Cập nhật trạng thái tất cả đồ án",
        "project",
    ),
    route(
        "PUT",
        "/api/projects/guiders/reception-status/:projectId",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPDATE",
        "Cập nhật trạng thái tiếp nhận hướng dẫn",
        "project",
        "projectId",
    ),
    route(
        "PUT",
        "/api/projects/guiders/approval-status/:projectId",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "APPROVE",
        "Phê duyệt hướng dẫn đồ án",
        "project",
        "projectId",
    ),
    route(
        "PUT",
        "/api/projects/guiders/info-project/:projectId",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPDATE",
        "Cập nhật thông tin đồ án",
        "project",
        "projectId",
    ),
    route(
        "PUT",
        "/api/projects/reviewers",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPDATE",
        "Phân công phản biện đồ án",
        "project",
    ),
    route(
        "PUT",
        "/api/projects/reviewers/:projectId",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "DELETE",
        "Gỡ phản biện đồ án",
        "project",
        "projectId",
    ),
    route(
        "POST",
        "/api/projects/assign-guider",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPDATE",
        "Phân công hướng dẫn đồ án",
        "project",
    ),
    route(
        "POST",
        "/api/projects/assign-reviewer-company",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPDATE",
        "Phân công phản biện doanh nghiệp",
        "project",
    ),
    route(
        "POST",
        "/api/projects/:projectId/members/:studentRef/approve",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "APPROVE",
        "Phê duyệt thành viên đồ án",
        "project",
        "projectId",
    ),
    route(
        "POST",
        "/api/projects/:projectId/members/:studentRef/reject",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "REJECT",
        "Từ chối thành viên đồ án",
        "project",
        "projectId",
    ),
    route(
        "POST",
        "/api/projects/reports/replies/:projectId/:reportKey",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "CREATE",
        "Phản hồi báo cáo đồ án",
        "project",
        "projectId",
    ),
    route(
        "PUT",
        "/api/projects/reports/replies/:projectId/:reportKey/:replyId",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPDATE",
        "Cập nhật phản hồi báo cáo đồ án",
        "project",
        "projectId",
    ),
    route(
        "POST",
        "/api/projects/reports",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "CREATE",
        "Nộp báo cáo tiến độ đồ án",
        "project",
    ),
    route(
        "PUT",
        "/api/projects/reports",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPDATE",
        "Cập nhật báo cáo tiến độ đồ án",
        "project",
    ),
    route(
        "POST",
        "/api/projects/timelines",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "CREATE",
        "Tạo mốc thời gian đồ án",
        "project-timeline",
    ),
    route(
        "PUT",
        "/api/projects/timelines/:key",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPDATE",
        "Cập nhật mốc thời gian đồ án",
        "project-timeline",
        "key",
    ),
    route(
        "DELETE",
        "/api/projects/timelines/:key",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "DELETE",
        "Xóa mốc thời gian đồ án",
        "project-timeline",
        "key",
    ),
    route(
        "POST",
        "/api/projects/pre-report-files/upload",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPLOAD",
        "Tải tệp trước bảo vệ lên",
        "project",
    ),
    route(
        "PUT",
        "/api/projects/pre-report-files/update-status/:projectId",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPDATE",
        "Cập nhật trạng thái tệp trước bảo vệ",
        "project",
        "projectId",
    ),
    route(
        "GET",
        "/api/projects/pre-report-files/download/:projectId",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "DOWNLOAD",
        "Tải tệp trước bảo vệ",
        "project",
        "projectId",
    ),
    route(
        "POST",
        "/api/projects/post-report-files/upload",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPLOAD",
        "Tải tệp sau bảo vệ lên",
        "project",
    ),
    route(
        "PUT",
        "/api/projects/post-report-files/update-status/guider/:projectId",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPDATE",
        "Cập nhật trạng thái tệp sau bảo vệ bởi hướng dẫn",
        "project",
        "projectId",
    ),
    route(
        "PUT",
        "/api/projects/post-report-files/update-status/committee/:projectId",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPDATE",
        "Cập nhật trạng thái tệp sau bảo vệ bởi hội đồng",
        "project",
        "projectId",
    ),
    route(
        "GET",
        "/api/projects/post-report-files/download/:projectId",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "DOWNLOAD",
        "Tải tệp sau bảo vệ",
        "project",
        "projectId",
    ),
    route(
        "DELETE",
        "/api/projects/committees",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "DELETE",
        "Xóa hội đồng đồ án",
        "project-committee",
    ),
    route(
        "GET",
        "/api/projects/committees/:committeeId/export-excel",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "EXPORT",
        "Xuất chi tiết hội đồng đồ án",
        "project-committee",
        "committeeId",
    ),
    route(
        "GET",
        "/api/projects/committees/export-excel",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "EXPORT",
        "Xuất danh sách hội đồng đồ án",
        "project-committee",
    ),
    route(
        "POST",
        "/api/projects/committees",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "CREATE",
        "Tạo hội đồng đồ án",
        "project-committee",
    ),
    route(
        "POST",
        "/api/projects/committees/add",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "CREATE",
        "Thêm hội đồng đồ án",
        "project-committee",
    ),
    route(
        "PUT",
        "/api/projects/committees/assign-roles",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPDATE",
        "Phân vai trò hội đồng đồ án",
        "project-committee",
    ),
    route(
        "PUT",
        "/api/projects/committees/assign-members",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPDATE",
        "Phân thành viên hội đồng đồ án",
        "project-committee",
    ),
    route(
        "PUT",
        "/api/projects/committees/remove-members",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "DELETE",
        "Gỡ thành viên hội đồng đồ án",
        "project-committee",
    ),
    route(
        "PUT",
        "/api/projects/committees/assign-projects",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPDATE",
        "Phân đồ án vào hội đồng",
        "project-committee",
    ),
    route(
        "PUT",
        "/api/projects/committees/remove-projects",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "DELETE",
        "Gỡ đồ án khỏi hội đồng",
        "project-committee",
    ),
    route(
        "PUT",
        "/api/projects/committees/project-order",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPDATE",
        "Cập nhật thứ tự bảo vệ đồ án",
        "project-committee",
    ),
    route(
        "GET",
        "/api/projects/exports/approval",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "EXPORT",
        "Xuất danh sách phê duyệt đồ án",
        "project",
    ),
    route(
        "GET",
        "/api/projects/exports/registration-decision",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "EXPORT",
        "Xuất quyết định đăng ký đồ án",
        "project",
    ),
    route(
        "POST",
        "/api/projects/exports/report-files",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "EXPORT",
        "Xuất kho báo cáo đồ án",
        "project",
    ),
    route(
        "GET",
        "/api/projects/minutes/:committeeId/export-docx",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "EXPORT",
        "Xuất biên bản hội đồng đồ án",
        "project-committee",
        "committeeId",
    ),
    route(
        "POST",
        "/api/projects/minutes",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "CREATE",
        "Tạo biên bản hội đồng đồ án",
        "project-committee",
    ),
    route(
        "PUT",
        "/api/projects/minutes/:committeeId/:projectId",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPDATE",
        "Cập nhật biên bản đồ án",
        "project",
        "projectId",
    ),
    route(
        "POST",
        "/api/projects/evaluations-result",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "CREATE",
        "Chấm điểm đồ án",
        "project",
    ),
    route(
        "PUT",
        "/api/projects/evaluations-result",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "UPDATE",
        "Cập nhật điểm đồ án",
        "project",
    ),
    route(
        "GET",
        "/api/projects/evaluations-result/export/total-gpa/guider",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "EXPORT",
        "Xuất tiến độ chấm hướng dẫn",
        "project",
    ),
    route(
        "GET",
        "/api/projects/evaluations-result/export/total-gpa/reviewer",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "EXPORT",
        "Xuất điểm phản biện",
        "project",
    ),
    route(
        "GET",
        "/api/projects/evaluations-result/export/total-gpa/member",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "EXPORT",
        "Xuất điểm hội đồng",
        "project",
    ),
    route(
        "GET",
        "/api/projects/evaluations-result/export/total-gpa/faculty",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "EXPORT",
        "Xuất điểm đồ án theo khoa",
        "project",
    ),
    route(
        "PATCH",
        "/api/projects/evaluations-result/publish/:academicYearId",
        "graduation-project",
        "Đồ án tốt nghiệp",
        "APPROVE",
        "Công bố kết quả đồ án",
        "academic-year",
        "academicYearId",
    ),

    // Nghiên cứu khoa học
    route(
        "POST",
        "/api/researches",
        "research",
        "Nghiên cứu khoa học",
        "CREATE",
        "Đăng ký nghiên cứu",
        "research",
    ),
    route(
        "PUT",
        "/api/researches/approval-status/:researchId",
        "research",
        "Nghiên cứu khoa học",
        "APPROVE",
        "Phê duyệt nghiên cứu",
        "research",
        "researchId",
    ),
    route(
        "POST",
        "/api/researches/comment",
        "research",
        "Nghiên cứu khoa học",
        "CREATE",
        "Thêm nhận xét nghiên cứu",
        "research",
    ),
    route(
        "POST",
        "/api/researches/final-committee/reviewer",
        "research",
        "Nghiên cứu khoa học",
        "UPDATE",
        "Phân công phản biện nghiên cứu",
        "research",
    ),
    route(
        "POST",
        "/api/researches/final-committee/reviewer/:researchId",
        "research",
        "Nghiên cứu khoa học",
        "DELETE",
        "Gỡ phản biện nghiên cứu",
        "research",
        "researchId",
    ),
    route(
        "PUT",
        "/api/researches/level/:researchId",
        "research",
        "Nghiên cứu khoa học",
        "UPDATE",
        "Cập nhật cấp nghiên cứu",
        "research",
        "researchId",
    ),
    route(
        "PUT",
        "/api/researches/:researchId",
        "research",
        "Nghiên cứu khoa học",
        "UPDATE",
        "Cập nhật nghiên cứu",
        "research",
        "researchId",
    ),
    route(
        "POST",
        "/api/researches/timelines",
        "research",
        "Nghiên cứu khoa học",
        "CREATE",
        "Tạo mốc thời gian nghiên cứu",
        "research-timeline",
    ),
    route(
        "PUT",
        "/api/researches/timelines/:key",
        "research",
        "Nghiên cứu khoa học",
        "UPDATE",
        "Cập nhật mốc thời gian nghiên cứu",
        "research-timeline",
        "key",
    ),
    route(
        "DELETE",
        "/api/researches/timelines/:key",
        "research",
        "Nghiên cứu khoa học",
        "DELETE",
        "Xóa mốc thời gian nghiên cứu",
        "research-timeline",
        "key",
    ),
    route(
        "GET",
        "/api/researches/pre-acceptance-reports/download",
        "research",
        "Nghiên cứu khoa học",
        "DOWNLOAD",
        "Tải báo cáo trước nghiệm thu",
        "research",
    ),
    route(
        "GET",
        "/api/researches/pre-acceptance-reports/accessible/download",
        "research",
        "Nghiên cứu khoa học",
        "DOWNLOAD",
        "Tải báo cáo nghiên cứu được phân quyền",
        "research",
    ),
    route(
        "POST",
        "/api/researches/pre-acceptance-reports/upload",
        "research",
        "Nghiên cứu khoa học",
        "UPLOAD",
        "Tải báo cáo trước nghiệm thu lên",
        "research",
    ),
    route(
        "PUT",
        "/api/researches/pre-acceptance-reports/:researchId/review",
        "research",
        "Nghiên cứu khoa học",
        "APPROVE",
        "Duyệt báo cáo trước nghiệm thu",
        "research",
        "researchId",
    ),
    route(
        "GET",
        "/api/researches/post-acceptance-reports/download",
        "research",
        "Nghiên cứu khoa học",
        "DOWNLOAD",
        "Tải báo cáo sau nghiệm thu",
        "research",
    ),
    route(
        "POST",
        "/api/researches/post-acceptance-reports/upload",
        "research",
        "Nghiên cứu khoa học",
        "UPLOAD",
        "Tải báo cáo sau nghiệm thu lên",
        "research",
    ),
    route(
        "GET",
        "/api/researches/committees/:committeeId/export-excel-detail",
        "research",
        "Nghiên cứu khoa học",
        "EXPORT",
        "Xuất chi tiết hội đồng nghiên cứu",
        "research-committee",
        "committeeId",
    ),
    route(
        "GET",
        "/api/researches/committees/:type/export-excel",
        "research",
        "Nghiên cứu khoa học",
        "EXPORT",
        "Xuất danh sách hội đồng nghiên cứu",
        "research-committee",
        "type",
    ),
    route(
        "DELETE",
        "/api/researches/committees/:type",
        "research",
        "Nghiên cứu khoa học",
        "DELETE",
        "Xóa hội đồng nghiên cứu",
        "research-committee",
        "type",
    ),
    route(
        "POST",
        "/api/researches/committees/assign-lecturers",
        "research",
        "Nghiên cứu khoa học",
        "UPDATE",
        "Phân giảng viên vào hội đồng nghiên cứu",
        "research-committee",
    ),
    route(
        "POST",
        "/api/researches/committees/remove-lecturers",
        "research",
        "Nghiên cứu khoa học",
        "DELETE",
        "Gỡ giảng viên khỏi hội đồng nghiên cứu",
        "research-committee",
    ),
    route(
        "POST",
        "/api/researches/committees/assign-researches",
        "research",
        "Nghiên cứu khoa học",
        "UPDATE",
        "Phân đề tài vào hội đồng nghiên cứu",
        "research-committee",
    ),
    route(
        "POST",
        "/api/researches/committees/remove-researches",
        "research",
        "Nghiên cứu khoa học",
        "DELETE",
        "Gỡ đề tài khỏi hội đồng nghiên cứu",
        "research-committee",
    ),
    route(
        "POST",
        "/api/researches/committees/:type",
        "research",
        "Nghiên cứu khoa học",
        "CREATE",
        "Tạo hội đồng nghiên cứu",
        "research-committee",
        "type",
    ),
    route(
        "POST",
        "/api/researches/committees/:type/add",
        "research",
        "Nghiên cứu khoa học",
        "CREATE",
        "Thêm hội đồng nghiên cứu",
        "research-committee",
        "type",
    ),
    route(
        "PATCH",
        "/api/researches/committees/:id/:type/topic-type",
        "research",
        "Nghiên cứu khoa học",
        "UPDATE",
        "Cập nhật loại đề tài hội đồng",
        "research-committee",
        "id",
    ),
    route(
        "PUT",
        "/api/researches/committees/assign-roles",
        "research",
        "Nghiên cứu khoa học",
        "UPDATE",
        "Phân vai trò hội đồng nghiên cứu",
        "research-committee",
    ),
    route(
        "PUT",
        "/api/researches/committees/research-order",
        "research",
        "Nghiên cứu khoa học",
        "UPDATE",
        "Cập nhật thứ tự nghiệm thu",
        "research-committee",
    ),
    route(
        "PUT",
        "/api/researches/committees/attendees",
        "research",
        "Nghiên cứu khoa học",
        "UPDATE",
        "Cập nhật người tham dự hội đồng",
        "research-committee",
    ),
    route(
        "PUT",
        "/api/researches/committees/outside-attendees",
        "research",
        "Nghiên cứu khoa học",
        "UPDATE",
        "Thêm khách mời hội đồng",
        "research-committee",
    ),
    route(
        "PUT",
        "/api/researches/committees-config",
        "research",
        "Nghiên cứu khoa học",
        "UPDATE",
        "Cập nhật cấu hình hội đồng nghiên cứu",
        "research-committee",
    ),
    route(
        "PUT",
        "/api/researches/committees-config/time-location/:committeeId",
        "research",
        "Nghiên cứu khoa học",
        "UPDATE",
        "Cập nhật thời gian và địa điểm hội đồng nghiên cứu",
        "research-committee",
        "committeeId",
    ),
    route(
        "POST",
        "/api/researches/expense-committees/:type",
        "research",
        "Nghiên cứu khoa học",
        "UPDATE",
        "Lưu chi phí hội đồng nghiên cứu",
        "research-committee",
        "type",
    ),
    route(
        "GET",
        "/api/researches/expense-committees/:researchId/committee-expense-detail/excel",
        "research",
        "Nghiên cứu khoa học",
        "EXPORT",
        "Xuất chi tiết chi phí hội đồng",
        "research",
        "researchId",
    ),
    route(
        "GET",
        "/api/researches/expense-committees/summary/seminar/excel",
        "research",
        "Nghiên cứu khoa học",
        "EXPORT",
        "Xuất tổng hợp chi phí seminar",
        "research-committee",
    ),
    route(
        "GET",
        "/api/researches/expense-committees/summary/member/:type/excel",
        "research",
        "Nghiên cứu khoa học",
        "EXPORT",
        "Xuất tổng hợp chi phí thành viên",
        "research-committee",
        "type",
    ),
    route(
        "POST",
        "/api/researches/minutes",
        "research",
        "Nghiên cứu khoa học",
        "CREATE",
        "Tạo biên bản hội đồng nghiên cứu",
        "research-committee",
    ),
    route(
        "PUT",
        "/api/researches/minutes/discussion-record",
        "research",
        "Nghiên cứu khoa học",
        "UPDATE",
        "Cập nhật thảo luận hội đồng nghiên cứu",
        "research-committee",
    ),
    route(
        "PUT",
        "/api/researches/minutes/:minutesId",
        "research",
        "Nghiên cứu khoa học",
        "UPDATE",
        "Cập nhật biên bản hội đồng nghiên cứu",
        "research-minutes",
        "minutesId",
    ),
    route(
        "GET",
        "/api/researches/minutes/:committeeId/:researchId/export-docx",
        "research",
        "Nghiên cứu khoa học",
        "EXPORT",
        "Xuất biên bản hội đồng nghiên cứu",
        "research",
        "researchId",
    ),

    // Tệp và biểu mẫu dùng chung
    route(
        "GET",
        "/api/files/download",
        "file",
        "Tệp",
        "DOWNLOAD",
        "Tải tệp",
        "file",
    ),
    route(
        "GET",
        "/api/templates/download",
        "template",
        "Biểu mẫu",
        "DOWNLOAD",
        "Tải biểu mẫu",
        "template",
    ),
];

const splitPath = (value) => value.split("/").filter(Boolean);
const routesBySpecificity = [...USER_ACTIVITY_ROUTES].sort((left, right) => {
    const leftSegments = splitPath(left.path);
    const rightSegments = splitPath(right.path);

    const segmentCount = Math.min(leftSegments.length, rightSegments.length);
    for (let index = 0; index < segmentCount; index += 1) {
        const difference =
            Number(leftSegments[index].startsWith(":")) -
            Number(rightSegments[index].startsWith(":"));
        if (difference !== 0) return difference;
    }

    return 0;
});

const resolveUserActivity = (method, originalUrl) => {
    let pathname;
    try {
        pathname = new URL(originalUrl, "http://localhost").pathname;
    } catch {
        return null;
    }
    const pathSegments = splitPath(pathname);

    for (const definition of routesBySpecificity) {
        if (definition.method !== method) continue;

        const templateSegments = splitPath(definition.path);
        if (templateSegments.length !== pathSegments.length) continue;

        const params = {};
        let matched = true;
        for (let index = 0; index < templateSegments.length; index += 1) {
            const templateSegment = templateSegments[index];
            const pathSegment = pathSegments[index];
            if (templateSegment.startsWith(":")) {
                try {
                    params[templateSegment.slice(1)] =
                        decodeURIComponent(pathSegment);
                } catch {
                    matched = false;
                    break;
                }
            } else if (templateSegment !== pathSegment) {
                matched = false;
                break;
            }
        }
        if (!matched) continue;

        return {
            featureCode: definition.featureCode,
            featureLabel: definition.featureLabel,
            actionCode: definition.actionCode,
            actionLabel: definition.actionLabel,
            targetType: definition.targetType,
            targetId: definition.targetParam
                ? params[definition.targetParam]
                : undefined,
        };
    }

    return null;
};

module.exports = { USER_ACTIVITY_ROUTES, resolveUserActivity };
